import React from "react";

import { Form, useActionData, redirect } from "react-router-dom";
import api from "../api/axios";

/**
 * Component to create a single inventory item.
 * @returns
 */
export default function CreateInventoryItem() {
  // The useActionData() hook allows us access to the return data
  // from the createInventoryItemAction() below.
  // We can use it to inform any form updates/responses here.
  const data = useActionData();
  return (
    <div className="contact">
      <h3>Create Inventory Item</h3>
      <Form method="post" action="/createinventoryitem">
        <label>
          <span>Item Name:</span>
          <input type="message" name="itemname" required />
        </label>
        <label>
          <span>Quantity:</span>
          <input
            type="number"
            step="1"
            min="0"
            onKeyDown={(e) =>
              !/[0-9\x7F\u2190]/.test(e.key) && e.preventDefault()
            }
            name="quantity"
            required
          />
        </label>
        <label>
          <span>Description:</span>
          <textarea type="message" name="description" required></textarea>
        </label>
        <button>Create Inventory Item</button>
        {/* Check if the data from the createInventoryItemAction() below
            returned an error. If so, show the user. */}
        {data && data.error && <p>{data.error}</p>}
      </Form>
    </div>
  );
}

/**
 * Handler for form data above.
 * @param {request} Contains the form data.
 * @returns
 */
export const createInventoryItemAction =
  ({ auth }) =>
  async ({ request }) => {
    // Pre-condition: User is logged in
    const userName = auth.userName;
    //  console.log(request);
    try {
      // Build the new inventoryItem
      const data = await request.formData();
      //      console.log("createInventoryItemAction> data: ");
      //      console.log(data);

      console.log("createInventoryItemAction> userName: " + userName);
      const newInventoryItem = {
        //    id: auto generated by mongodb
        owner: userName,
        modifieddate: new Date().toLocaleString(),
        itemname: data.get("itemname"),
        quantity: data.get("quantity"),
        description: data.get("description"),
      };
      //    console.log("createInventoryItemAction> newInventoryItem: " + JSON.stringify(newInventoryItem));

      // Next, submit the new post
      await api.post("/inventoryitems", newInventoryItem);
    } catch (err) {
      if (err.response) {
        // Not in the 200 response range
        console.log(err.response.data);
        console.log(err.response.status);
        console.log(err.response.headers);
      } else {
        // No response or non-200 error
        console.log(`createInventoryItemAction> Error: ${err.message}`);
      }
    }

    // redirect the user
    return redirect("/inventoryitems/" + userName);
  };
